// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zuscrzwfggfwnwfnljje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1c2NyendmZ2dmd253Zm5samplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNzY5NDEsImV4cCI6MjA3MDc1Mjk0MX0.Yb0-ksx3LlaxgaxBfa_y-s55Ai1Qe4eUv-dPpcYLu8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});